"""Etapa 2: as 7 tabelas do sistema

Revision ID: 7105d4265a12
Revises: 
Create Date: 2026-09-22 16:11:23.267562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7105d4265a12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('deve_trocar_senha', sa.Boolean(), nullable=False),
    sa.Column('papel', sa.Enum('admin', 'responsavel', name='papel_usuario', native_enum=False), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario'))
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_login'), ['login'], unique=True)

    op.create_table('evento',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('tipo', sa.Enum('culto_dominical', 'culto_ensino', 'culto_ceia', 'encontro_tribo', 'trabalho_preciosas', 'outro', name='tipo_evento', native_enum=False), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('recorrente', sa.Boolean(), nullable=False),
    sa.Column('criado_por_id', sa.String(length=36), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuario.id'], name=op.f('fk_evento_criado_por_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evento')),
    sa.UniqueConstraint('tipo', 'data', name='evento_unico_por_tipo_e_data')
    )
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evento_data'), ['data'], unique=False)

    op.create_table('log_auditoria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=True),
    sa.Column('entidade_id', sa.String(length=36), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_log_auditoria_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_log_auditoria'))
    )
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_auditoria_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_auditoria_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('novo_convertido',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=True),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', name='sexo', native_enum=False), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=True),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('trabalho', sa.Enum('culto_dominical', 'culto_ensino', 'culto_ceia', 'encontro_tribo', 'evangelismo_rua', 'trabalho_preciosas', 'outro', name='trabalho_conversao', native_enum=False), nullable=False),
    sa.Column('trabalho_outro', sa.String(length=120), nullable=True),
    sa.Column('data_conversao', sa.Date(), nullable=False),
    sa.Column('departamento', sa.Enum('geracao_life', 'preciosas', 'irmaos', name='departamento', native_enum=False), nullable=False),
    sa.Column('como_chegou', sa.Text(), nullable=True),
    sa.Column('tem_conhecido', sa.Boolean(), nullable=True),
    sa.Column('conhecido_nome', sa.String(length=150), nullable=True),
    sa.Column('ja_frequentou_igreja', sa.Boolean(), nullable=True),
    sa.Column('qual_igreja', sa.String(length=150), nullable=True),
    sa.Column('cadastrante_nome', sa.String(length=150), nullable=False),
    sa.Column('cadastrante_telefone', sa.String(length=20), nullable=False),
    sa.Column('consentimento_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consentimento_ip', sa.String(length=45), nullable=True),
    sa.Column('responsavel_legal_nome', sa.String(length=150), nullable=True),
    sa.Column('responsavel_legal_telefone', sa.String(length=20), nullable=True),
    sa.Column('status_ciclo', sa.Enum('aguardando_responsavel', 'em_acompanhamento', 'integrado', 'frequenta_outra_igreja', 'nao_deseja_contato', 'perdido_contato', 'mudou_cidade', name='status_ciclo', native_enum=False), nullable=False),
    sa.Column('status_justificativa', sa.Text(), nullable=True),
    sa.Column('status_alterado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responsavel_atual_id', sa.String(length=36), nullable=True),
    sa.Column('designado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mesclado_em_id', sa.String(length=36), nullable=True),
    sa.Column('observacao_sensivel', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mesclado_em_id'], ['novo_convertido.id'], name=op.f('fk_novo_convertido_mesclado_em_id_novo_convertido')),
    sa.ForeignKeyConstraint(['responsavel_atual_id'], ['usuario.id'], name=op.f('fk_novo_convertido_responsavel_atual_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_novo_convertido'))
    )
    with op.batch_alter_table('novo_convertido', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_novo_convertido_codigo'), ['codigo'], unique=True)
        batch_op.create_index(batch_op.f('ix_novo_convertido_criado_em'), ['criado_em'], unique=False)
        batch_op.create_index(batch_op.f('ix_novo_convertido_departamento'), ['departamento'], unique=False)
        batch_op.create_index(batch_op.f('ix_novo_convertido_nome_completo'), ['nome_completo'], unique=False)
        batch_op.create_index(batch_op.f('ix_novo_convertido_responsavel_atual_id'), ['responsavel_atual_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_novo_convertido_status_ciclo'), ['status_ciclo'], unique=False)
        batch_op.create_index(batch_op.f('ix_novo_convertido_telefone'), ['telefone'], unique=False)
        batch_op.create_index('ix_painel_status_responsavel', ['status_ciclo', 'responsavel_atual_id'], unique=False)

    op.create_table('atribuicao',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('convertido_id', sa.String(length=36), nullable=False),
    sa.Column('responsavel_id', sa.String(length=36), nullable=False),
    sa.Column('inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('atribuido_por_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['atribuido_por_id'], ['usuario.id'], name=op.f('fk_atribuicao_atribuido_por_id_usuario')),
    sa.ForeignKeyConstraint(['convertido_id'], ['novo_convertido.id'], name=op.f('fk_atribuicao_convertido_id_novo_convertido')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], name=op.f('fk_atribuicao_responsavel_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_atribuicao'))
    )
    with op.batch_alter_table('atribuicao', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_atribuicao_convertido_id'), ['convertido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_atribuicao_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('contato',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('convertido_id', sa.String(length=36), nullable=False),
    sa.Column('responsavel_id', sa.String(length=36), nullable=False),
    sa.Column('tipo', sa.Enum('telefone', 'whatsapp', 'presencial', name='tipo_contato', native_enum=False), nullable=False),
    sa.Column('data_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resultado', sa.Enum('efetivo', 'sem_resposta', 'recusou_contato', name='resultado_contato', native_enum=False), nullable=False),
    sa.Column('relato', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['convertido_id'], ['novo_convertido.id'], name=op.f('fk_contato_convertido_id_novo_convertido')),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuario.id'], name=op.f('fk_contato_responsavel_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contato'))
    )
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contato_convertido_id'), ['convertido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contato_data_hora'), ['data_hora'], unique=False)
        batch_op.create_index(batch_op.f('ix_contato_responsavel_id'), ['responsavel_id'], unique=False)

    op.create_table('presenca',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('convertido_id', sa.String(length=36), nullable=False),
    sa.Column('evento_id', sa.String(length=36), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('registrado_por_id', sa.String(length=36), nullable=False),
    sa.Column('registrado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['convertido_id'], ['novo_convertido.id'], name=op.f('fk_presenca_convertido_id_novo_convertido')),
    sa.ForeignKeyConstraint(['evento_id'], ['evento.id'], name=op.f('fk_presenca_evento_id_evento')),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['usuario.id'], name=op.f('fk_presenca_registrado_por_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_presenca')),
    sa.UniqueConstraint('convertido_id', 'evento_id', name='presenca_unica_por_evento')
    )
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_presenca_convertido_id'), ['convertido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_presenca_evento_id'), ['evento_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_presenca_evento_id'))
        batch_op.drop_index(batch_op.f('ix_presenca_convertido_id'))

    op.drop_table('presenca')
    with op.batch_alter_table('contato', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contato_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_contato_data_hora'))
        batch_op.drop_index(batch_op.f('ix_contato_convertido_id'))

    op.drop_table('contato')
    with op.batch_alter_table('atribuicao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_atribuicao_responsavel_id'))
        batch_op.drop_index(batch_op.f('ix_atribuicao_convertido_id'))

    op.drop_table('atribuicao')
    with op.batch_alter_table('novo_convertido', schema=None) as batch_op:
        batch_op.drop_index('ix_painel_status_responsavel')
        batch_op.drop_index(batch_op.f('ix_novo_convertido_telefone'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_status_ciclo'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_responsavel_atual_id'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_nome_completo'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_departamento'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_criado_em'))
        batch_op.drop_index(batch_op.f('ix_novo_convertido_codigo'))

    op.drop_table('novo_convertido')
    with op.batch_alter_table('log_auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_auditoria_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_log_auditoria_criado_em'))
        batch_op.drop_index(batch_op.f('ix_log_auditoria_acao'))

    op.drop_table('log_auditoria')
    with op.batch_alter_table('evento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evento_data'))

    op.drop_table('evento')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_login'))

    op.drop_table('usuario')
    # ### end Alembic commands ###
