"""Etapa 2: tabela contador do codigo sequencial

Revision ID: a0508df9d687
Revises: 7105d4265a12
Create Date: 2026-09-22 16:13:19.092387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0508df9d687'
down_revision = '7105d4265a12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contador',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nome', name=op.f('pk_contador'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contador')
    # ### end Alembic commands ###
